### ISSUE TITLE
pyenv_virtualenvs does not create virtualenvs

### ISSUE THREAD

**Issue by nuclon** [kmezynski/ansible-role-pyenv#20]
### Describe the bug

According to the documentation, pyenv_virtualenvs should contain list of virtualenvs to create. It looks like, it does not work:
```
pyenv_python_versions:
  - 3.12.1
pyenv_default_python: 3.12.1
pyenv_virtualenvs:
  - name: udf
    version: 3.12.1
```
It does not create "udf" virtualenv

### Describe the expected behaviour

Virtualenv is created

### OS specs

debian 12.4

### Ansible version

ansible [core 2.16.2]

### Molecule version

x.y.z
